- src/const.h
- src/gd_midiGrabber.cpp
- src/gd_midiOutputSetup.cpp
- src/gd_midiOutputSetup.h
- src/ge_mixed.cpp
- src/ge_mixed.h
- src/midiChannel.cpp
- src/midiChannel.h
These changes add the ability to send midi program change and bank select messages on a per channel basis, for midi channels. They are sent when the channel goes into play mode by clicking the activate button. These functions are controlled on the midi output dialog box.
Also fixed with this update is the widget crowding issue on the midi input dialog box. Both midi dialog boxes have been enlarged. Also fixed was a long-standing issue where midi ALL_NOTES_OFF messages where not getting sent out correctly, and appeared to be having no useful effect; they were appearing as note-off for C with a velocity of -1.
> Midi tunnel

- src/conf.cpp
as [reported in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=791544), the code that checks the validity of the configured soundsystem breaks when compiling with g++5 and strict format checking (`-Werror  -Wformat -Werror=format-security`).
indeed the check is valid and th ecode is bogus: `(!soundSystem & (SYS_API_ANY))` is really `((!soundSystem) & (SYS_API_ANY))`.
this will only evaluate to true is `soundSystem==0`, in which here is no need to `&` it with `SYS_API_ANY`.
i think my patch is closer to the original intention (use the default soundsystem if no other soundsystem is chosen explicitely)
> fix check for configured soundsystem

- src/gui/elems/config/tabPlugins.cpp
See #132 . `tabPlugins.cpp` was looking to levels up (`../../`) for includes in `src/core` and `src/utils`; other files in this directory point three levels up (`../../../`).
> fixed src/gui/elems/config/tabPlugins.cpp relative paths

- src/main.cpp
I replaced the pthread calls and variables with the standard threads used in the C++ library.
I also made use of an anonymous namespace and fixed some indentation.
> Use Standard Library Thread

- src/core/init.cpp
`src/core/init.cpp` is missing an include for `atomic` leading to undefined type errors for `G_quit` on gcc 8.2.1 (and most likely much earlier already).
> Include missing atomic include

- src/core/conf.cpp
- src/core/conf.h
- src/core/const.h
- src/gui/elems/basics/dial.cpp
- src/gui/elems/basics/dial.h
- src/gui/elems/config/tabBehaviors.cpp
- src/gui/elems/config/tabBehaviors.h
Hi,
this PR adds linear dial control (instead of circular) and allows this to be configured. Furthermore, the linear mode also supports mousewheel input.
I've tested this with linux. Unfortunately, I couldn't test other platforms. 
Please let me know if there is anything missing.  
Regards,
Mathias
> feat() Adds toggle to enable linear dial controls

- .gitignore
- create_source_tarball.sh
create_source_tarball.sh:
Adding a script to create a source tarball from an existing tag in this
repository.
Call with ./create_source_tarball.sh -v <tag> to create a source tarball
including all git submodules next to the script.
Call with ./create_source_tarball.sh -v <tag> -s <pgp id or email> to
create a source tarball including all git submodules and additionally a
detached PGP signature next to the script.
.gitignore:
Adding *.tar.gz and *.tar.gz.asc to make sure not to accidentally
include generated source tarballs or detached PGP signatures to this
repository.
Closes #321
> Adding script to create source tarball.

- src/gui/elems/basics/choice.h
Apparently new GCC (>=10?) is more demanding about #includes.
> Add #include to choice.h (#412)

- Makefile.am
I couldn't link giada when doing the usual `./autogen.sh; configure --target=osx; make -j8` routine; I think this one file was missing from the build system. anyways this fixes it
> Add missing file to Makefile.am so giada builds

- src/gui/dialogs/browser/browserBase.h
src/gui/dialogs/browser/browserBase.h:
Add missing include for std::string.
Fixes #454
> Add missing include for std::string

- CMakeLists.txt
CMakeLists.txt:
Use the GNUInstallDirs module [1] to install the standalone executable
to the correct location on Unix-like systems.
Fixes #450
[1] https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html
> Install executable to FHS compliant location

- CMakeLists.txt
- extras/com.giadamusic.Giada.desktop
- extras/com.giadamusic.Giada.metainfo.xml
Add and install the freedesktop files. 
I use them for the flatpak https://github.com/flathub/flathub/pull/1626/
> Add Freedesktop files

- .gitmodules
Because of that, I couldn't properly fetch all submodules on my system (NixOS)
I think it'll be better to replace all `ssh` links with `http`. Anyway,  that change don't have strong affect
> Replacing all ssh links in .gitmodules with https

- CMakeLists.txt
Let cmake use -pthread instead of -lpthread, to fix build error on riscv64.
FYI:
https://stackoverflow.com/questions/23250863/difference-between-pthread-and-lpthread-while-compiling
https://stackoverflow.com/questions/1620918/cmake-and-libpthread
https://cmake.org/cmake/help/latest/module/FindThreads.html#variable:THREADS_PREFER_PTHREAD_FLAG
BTW: `${Threads_LIBRARY}` seems to be an undefined variable.
> Fix cmake pthread use

- extras/com.giadamusic.Giada.desktop
extras/com.giadamusic.Giada.desktop:
Use the correct file name for the logo (it is installed as
com.giadamusic.Giada.svg).
> Reference the correct icon in XDG desktop file

- src/core/actions/actionRecorder.cpp
- src/core/actions/actionRecorder.h
- src/core/kernelAudio.cpp
- src/core/kernelAudio.h
- src/core/midiDispatcher.cpp
- src/core/midiDispatcher.h
- src/core/midiLearnParam.cpp
- src/core/midiLearnParam.h
- src/core/midiMapper.cpp
- src/core/plugins/pluginHost.cpp
- src/core/plugins/pluginManager.cpp
- src/core/plugins/pluginState.cpp
- src/core/plugins/pluginState.h
- src/core/queue.h
- src/core/ringBuffer.h
- src/glue/config.cpp
- src/gui/dialogs/midiIO/midiInputChannel.cpp
- src/gui/elems/basics/flex.cpp
- src/gui/elems/basics/group.cpp
- src/gui/elems/basics/group.h
- src/gui/elems/basics/resizerBar.cpp
- src/gui/elems/basics/scrollPack.cpp
- src/gui/elems/basics/scrollPack.h
- src/utils/gui.cpp
- src/utils/string.cpp
- src/utils/vector.h
Include the `cstddef` header where `std::size_t` is used.
This is far from a full implementation of the “include what you use” concept, and indeed the [tool of that name](https://include-what-you-use.org/) could be helpful, but it does fix a concrete failure to compile on GCC 12.0.1, in which an implicit recursive include via another header was no longer present.
```
[159/172] /usr/bin/g++ -DNDEBUG -DTEST_RESOURCES_DIR=\"/builddir/build/BUILD/giada-0.20.1/tests/resources/\" -DWITH_AUDIO_JACK -DWITH_TESTS -D__LINUX_ALSA__ -D__LINUX_PULSE__ -D__UNIX_JACK__ -I/builddir/build/BUILD/giada-0.20.1 -I/builddir/build/BUILD/giada-0.20.1/src -isystem /usr/include/rtmidi -isystem /usr/include/opus -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall …
```
> Include <cstddef> where std::size_t is used

- .gitattributes
This PR adds a `.gitattributes` file, that makes sure that no repository and CI configuration is exported in the source tarballs.
Including repository configuration (like `.gitignore` or `.gitmodules`) and CI-configs (like `.github/workflows/*` or `.gitlab-ci.yml`) into the automatically generated source-tarballs (e.g. what you get when you click on the [Source code (tar.gz)](https://github.com/monocasual/giada/archive/refs/tags/v0.20.1.tar.gz) link for a release) if often harmful for downstreams:
- they won't be able to use things like `.gitmodules`anyhow, as they only get a tarball without the git-repository
- it interacts badly if they import the release tarball into their own git-repository
- this is really the thing that drives this PR. In Debian we are using *git* for tracking out …
> Exclude repository configuration from tarballs

- extras/com.giadamusic.Giada.desktop
This caused `desktop-file-validate` (from [desktop-file-utils](https://www.freedesktop.org/wiki/Software/desktop-file-utils/)) to fail.
Before:
```
$ desktop-file-validate extras/com.giadamusic.Giada.desktop 
extras/com.giadamusic.Giada.desktop: error: file contains multiple keys named "Comment" in group "Desktop Entry"
extras/com.giadamusic.Giada.desktop: warning: value "Drum machine and loop sequencer" for key "Comment" in group "Desktop Entry" looks the same as that of key "GenericName"
extras/com.giadamusic.Giada.desktop: warning: value "Drum machine and loop sequencer" for key "Comment" in group "Desktop Entry" looks the same as that of key "GenericName"
extras/com.giadamusic.Giada.desktop: warning: value "Drum Maschine und Loop Sequenzer" for key "Comment[de]" in group "Desktop …
```
> Remove duplicate Comment in desktop file

- src/gui/dialogs/about.cpp
- src/gui/dialogs/sampleEditor.cpp
- src/gui/elems/config/tabPlugins.cpp
fmt::format requires the non-static format argument to be wrapped with fmt::runtime check.
Fixes #634
> Fix build with fmt 9, GCC 12

- src/utils/log.h
```
[  4%] Building CXX object CMakeFiles/giada.dir/src/core/engine.cpp.o
In file included from /home/nedko/git/giada/src/core/engine.cpp:32:
/home/nedko/git/giada/src/utils/log.h:70:20: error: call to consteval function 'fmt::basic_format_string<char>::basic_format_string<const char *, 0>' is not a constant expression
fmt::print(file, format, args...);
^
/home/nedko/git/giada/src/core/engine.cpp:263:11: note: in instantiation of function template specialization 'giada::u::log::print<>' requested here
u::log::print("[Engine::shutdown] KernelAudio closed\n");
^
/usr/include/fmt/core.h:3148:67: note: function parameter 'format' with unknown value cannot be used in a constant expression
FMT_CONSTEVAL FMT_INLINE basic_format_string(const S& s) : str_(s) {
^ …
```
> Fix build (gentoo gcc-11 and clang-15 fail with same error)

- src/core/const.h
- src/gui/elems/midiIO/midiLearner.h
gcc-13 is a bit more strict when it comes to missing includes, resulting in FTBFS.
afaict, the github actions run on Ubuntu 20.04, which uses some rather dated compiler (gcc-10.3.0)
https://github.com/monocasual/giada/actions/runs/5662005386/job/15341078194#step:4:342
which explains why it doesn't catch build errors with newer compilers.
> Include <cstdint> for uint32_t
